"""followers

Revision ID: 21909b10b651
Revises: 90cdf8951279
Create Date: 2023-05-23 00:21:23.387279

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '21909b10b651'
down_revision = '90cdf8951279'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('followers',
    sa.Column('follower_id', sa.Integer(), nullable=True),
    sa.Column('followed_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('followers')
    # ### end Alembic commands ###
