"""empty message

Revision ID: 7035b0655a1a
Revises: d1138f212f19
Create Date: 2023-06-13 21:59:16.552079

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7035b0655a1a'
down_revision = 'd1138f212f19'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Data', sa.DateTime(), nullable=False),
    sa.Column('client', sa.String(length=100), nullable=False),
    sa.Column('item', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('order')
    # ### end Alembic commands ###
